### ISSUE TITLE
Create new npm version automatically whenever there is a commit into master

### ISSUE THREAD

**Issue by sponte** [oss-specs/specs#115]

**Comment by sponte** [comment]
This is now setup as a build in TeamCity. @jimCresswell make sure each pull request bumps a version to make sure we don't override packages.

**Comment by jimCresswell** [comment]
@sponte can we add a check in teamcity so it throws an error if a pull request doesn't up the version with respect to the npm one?

**Comment by jimCresswell** [comment]
https://www.npmjs.com/package/semver-compare

**Comment by sponte** [comment]
At the moment it just builds whenever master builds, best solution would be to make use of teamcity's build number to generate major.minor.build. What do you think? We would manage versioning inside TeamCity

**Comment by jimCresswell** [comment]
In principle it's a great idea, how would we determine whether to increment
major, minor or patch? Branch naming convention, commit message parsing?

**Comment by jimCresswell** [comment]
Then again, it's an app with no API, does strict semver even make sense in
this context? Could we always increment minor and set major manually?
