### ISSUE TITLE
Auto deployment of the latest app

### ISSUE THREAD

**Issue by sponte** [oss-specs/specs#35]

**Comment by jimCresswell** [comment]
So deploy master from teamcity if it passes tests?

**Comment by sponte** [comment]
Correct

**Comment by jimCresswell** [comment]
How exciting.

**Comment by jimCresswell** [comment]
Adding to beta milestone.

**Comment by jimCresswell** [comment]
In progress with @sponte

**Comment by sponte** [comment]
this is now done, can you confirm @jimCresswell and close the issue?

**Comment by sponte** [comment]
BTW - This is done in Heroku now. it integrates with github.com and automatically pushes. Heroku is awesome!

**Comment by jimCresswell** [comment]
Did you hear that @heroku, you are awesome :smile:

**Comment by jimCresswell** [comment]
Incidentally @sponte, would you mind making a few notes on all these integrations in the wiki, I'm losing track...

**Comment by jimCresswell** [comment]
Closing with happiness.
