### ISSUE TITLE
Document the integrations somewhere

### ISSUE THREAD

**Issue by jimCresswell** [oss-specs/specs#54]
This repo integrates with a TeamCity instance, dependency currency is checked on David, static analysis happens on Code Climate, there is monitoring in New Relic. All of that needs some configuration, either in this repo, Team City or the integrated service. It would be good to keep some notes of that, possibly in the [wiki](https://github.com/oss-specs/specs/wiki).

**Comment by sponte** [comment]
Will get to this at some point :) Currently no bandwidth

**Comment by jimCresswell** [comment]
No worries, I'll pick it up if I am free first

**Comment by jimCresswell** [comment]
@sponte did some work on this. Closing for now.
